---
.gitignore:
  paths:
    - .rake_tasks
    - .rvmrc

.pdkignore:
  paths:
    - /scripts/
    - .rake_tasks

spec/spec_helper.rb:
  mock_with: ':rspec'

Gemfile:
  optional:
    ":development":
      - gem: puppet-lint-i18n
      - gem: github_changelog_generator
        git: https://github.com/skywinder/github-changelog-generator
        ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
        condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')

Rakefile:
  changelog_user: andeman
